#!/bin/sh
LINUX_DISTRIBUTION=$(grep -Eo "(Debian|Ubuntu|RedHat|CentOS|openSUSE|Amazon)" /etc/issue)

if [ -f "/etc/debian_version" ] || [ "$LINUX_DISTRIBUTION" == "Debian" ] || [ "$LINUX_DISTRIBUTION" == "Ubuntu" ]; then
    set -e

    if [ "$1" = purge ]; then
        echo "Deleting sts-agent user"
        deluser sts-agent --quiet
        echo "Deleting sts-agent group"
        getent group sts-agent >/dev/null && delgroup sts-agent --quiet || true
        rm -rf /opt/stackstate-agent
        rm -rf /var/log/stackstate
        rm -rf /etc/sts-agent
        rm -rf /var/log/stackstate
    fi
elif [ -f "/etc/redhat-release" ] || [ "$LINUX_DISTRIBUTION" == "RedHat" ] || [ "$LINUX_DISTRIBUTION" == "CentOS" ] || [ "$LINUX_DISTRIBUTION" == "openSUSE" ] || [ "$LINUX_DISTRIBUTION" == "Amazon" ]; then
    case "$*" in
      0)
        # We're uninstalling.
        getent passwd sts-agent > /dev/null && userdel sts-agent
        getent group sts-agent >/dev/null && groupdel sts-agent
        ;;
      1)
        # We're upgrading.
        ;;
      *)
        ;;
    esac
else
      echo "[ ${Red}FAILED ${RCol}]\tYour system is currently not supported by this script.";
      exit 1;
fi
exit 0
